// <auto-generated />
namespace Real_Estate_Rest_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class checkingForChamges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkingForChamges));
        
        string IMigrationMetadata.Id
        {
            get { return "202102211615217_checkingForChamges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
